apiVersion: batch/v1
kind: Job
metadata:
  name: job-jkd22
spec:
  template:
    spec:
      automountServiceAccountToken: false
      containers:
      - name: job-baseball-jkd22
        image: gitlab-registry.nrp-nautilus.io/jmkramer87/ml_image:cf32ea7b
        tty: true
        stdin: true
        workingDir: /data/baseball/K8_Baseball
        command: ["/bin/sh","-c"]
        args: 
        - python3 batters.py;
        volumeMounts:
        - name: jkd22-pv
          mountPath: /data
        resources:
            limits:
              memory: 16Gi
              cpu: 4
            requests:
              memory: 16Gi
              cpu: 4
      volumes:
      - name: jkd22-pv 
        persistentVolumeClaim:
            claimName: jkd22-pv
      restartPolicy: Never      
  backoffLimit: 1

