apiVersion: batch/v1
kind: Job
metadata:
  name: job-kn
spec:
  template:
    spec:
      automountServiceAccountToken: false
      containers:
      - name: job-kn
        image: python:3.10
        tty: true
        stdin: true
        workingDir: /data/baseball/K8_Baseball
        command: ["/bin/sh","-c"]
        args: 
        -  pip install -r requirements.txt && python3 batters_kn.py 
        volumeMounts:
        - name: jkd22-pv
          mountPath: /data
        resources:
            limits:
              memory: 2Gi
              cpu: 6
            requests:
              memory: 2Gi
              cpu: 6
      volumes:
      - name: jkd22-pv 
        persistentVolumeClaim:
            claimName: jkd22-pv
      restartPolicy: Never      
  backoffLimit: 1

