apiVersion: batch/v1
kind: Job
metadata:
  name: pod-baseball-jkd22
spec:
  template:
    spec:
      automountServiceAccountToken: false
      containers:
      - name: pod-baseball-jkd22
        image: python:3.10
        tty: true
        stdin: true
        workingDir: /data
        command: ["/bin/sh","-c"]
        args: 
        - cp -r /jkd22/* /data/
        - python3 main.py;

        volumeMounts:
        - name: jkd22-pv
          mountPath: /data
        resources:
            limits:
              memory: 40Gi
              cpu: 1
            requests:
              memory: 40Gi
              cpu: 1
      volumes:
      - name: jkd22-pv 
        persistentVolumeClaim:
            claimName: jkd22-pv
      restartPolicy: Never      
  backoffLimit: 0

